title: Learning Loop
description: Blog sobre o cotidiano do programador
author: Learning Loop
logo: /Ikamihiro.github.io/static/img/logo.png
github: https://github.com/Ikamihiro
about: Mundo dos programadores

baseurl: ""
url: "https://ikamihiro.github.io/"

allowsearch: true


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
