title: Learning Loop
description: Blog sobre o cotidiano do programador
author: João e André
logo: /ikamihiro/static/img/logo.png
github: https://github.com/Ikamihiro
about: Developers

baseurl: ""
url: ""

allowsearch: true


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
